name: Convert and Publish Notebooks

on:
  push:
    branches:
      - main

jobs:
  convert-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.7

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.11'

    - name: Install Jupyter and Quarto
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert quarto-cli

    - name: Convert Notebooks to QMD
      run: |
        mkdir -p qmd
        for notebook in $(find . -name "*.ipynb"); do
          jupyter nbconvert --to markdown --output-dir=qmd "$notebook"
        done

    - name: Render QMD Files
      run: |
        for qmd in $(find qmd -name "*.md"); do
          quarto render "$qmd" --output-dir rendered
        done

    - name: Create Markdown Content
      run: |
        echo "# Portfolio" > rendered/index.md
        for rendered_file in $(find rendered -name "*.html"); do
          echo "- [$(basename "$rendered_file" .html)]($rendered_file)" >> rendered/index.md
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./rendered
